import { LinearGradient } from 'expo-linear-gradient';
import { PropsWithChildren } from 'react';
import { Modal, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import Svg, { Circle, Defs, LinearGradient as SvgGradient, Path, Stop } from 'react-native-svg';

export const palette = { bg: '#07090D', panel: '#12161D', panel2: '#191E27', text: '#F7F8FA', muted: '#89909D', lime: '#C9FF57', purple: '#9B7BFF', red: '#FF647C', green: '#5FE0A3', border: '#252B36' };
export function Card({ children, style }: PropsWithChildren<{ style?: object }>) { return <View style={[styles.card, style]}>{children}</View>; }
export function ProgressBar({ value, color = palette.lime }: { value: number; color?: string }) { const width = `${Math.max(0, Math.min(value, 1)) * 100}%` as `${number}%`; return <View style={styles.track}><View style={[styles.fill, { width, backgroundColor: color }]} /></View>; }
export function Ring({ value, label }: { value: number; label: string }) { const progress = Math.max(0, Math.min(value, 1)); const size = 94, stroke = 9, radius = (size - stroke) / 2, circumference = radius * Math.PI * 2; return <View style={{ width: size, height: size, alignItems: 'center', justifyContent: 'center' }}><Svg width={size} height={size} style={StyleSheet.absoluteFill}><Circle cx={size / 2} cy={size / 2} r={radius} stroke="#2B3038" strokeWidth={stroke} fill="none" /><Circle cx={size / 2} cy={size / 2} r={radius} stroke={palette.lime} strokeWidth={stroke} fill="none" strokeLinecap="round" strokeDasharray={`${circumference} ${circumference}`} strokeDashoffset={circumference * (1 - progress)} rotation="-90" origin={`${size / 2}, ${size / 2}`} /></Svg><Text style={styles.ringLabel}>{label}</Text></View>; }
export function LineChart({ values }: { values: number[] }) { const width = 330, height = 170, pad = 10; const series = values.length > 1 ? values : [values[0] || 0, values[0] || 0]; const min = Math.min(...series, 0), max = Math.max(...series, 1), range = max - min || 1; const points = series.map((value, index) => ({ x: pad + index * ((width - pad * 2) / (series.length - 1)), y: height - pad - ((value - min) / range) * (height - pad * 2) })); const line = points.map((point, index) => `${index ? 'L' : 'M'} ${point.x} ${point.y}`).join(' '); const area = `${line} L ${points.at(-1)!.x} ${height} L ${points[0].x} ${height} Z`; return <Svg width="100%" height={height} viewBox={`0 0 ${width} ${height}`} preserveAspectRatio="none"><Defs><SvgGradient id="chart" x1="0" y1="0" x2="0" y2="1"><Stop offset="0" stopColor={palette.purple} stopOpacity=".42" /><Stop offset="1" stopColor={palette.purple} stopOpacity="0" /></SvgGradient></Defs><Path d={area} fill="url(#chart)" /><Path d={line} fill="none" stroke={palette.purple} strokeWidth="4" strokeLinecap="round" strokeLinejoin="round" />{points.map((point, i) => <Circle key={i} cx={point.x} cy={point.y} r={i === points.length - 1 ? 5 : 0} fill={palette.text} stroke={palette.purple} strokeWidth="3" />)}</Svg>; }
export function Sheet({ visible, title, onClose, children }: PropsWithChildren<{ visible: boolean; title: string; onClose: () => void }>) { return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><Pressable style={styles.backdrop} onPress={onClose} /><View style={styles.sheet}><View style={styles.handle} /><Text style={styles.sheetTitle}>{title}</Text>{children}</View></Modal>; }
export function Field(props: React.ComponentProps<typeof TextInput>) { return <TextInput placeholderTextColor="#656C78" {...props} style={[styles.input, props.style]} />; }
export function PrimaryButton({ label, onPress, disabled }: { label: string; onPress: () => void; disabled?: boolean }) { return <Pressable disabled={disabled} onPress={onPress} style={({ pressed }) => [{ opacity: disabled ? .4 : pressed ? .75 : 1 }]}><LinearGradient colors={[palette.lime, '#91E95B']} style={styles.button}><Text style={styles.buttonText}>{label}</Text></LinearGradient></Pressable>; }
const styles = StyleSheet.create({ card: { backgroundColor: palette.panel, borderRadius: 26, padding: 20, borderWidth: 1, borderColor: palette.border }, track: { height: 9, backgroundColor: '#2A3038', borderRadius: 9, overflow: 'hidden' }, fill: { height: '100%', borderRadius: 9 }, ringLabel: { color: palette.text, fontSize: 17, fontWeight: '800' }, backdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0,0,0,.7)' }, sheet: { position: 'absolute', bottom: 0, width: '100%', backgroundColor: palette.panel, borderTopLeftRadius: 32, borderTopRightRadius: 32, paddingHorizontal: 22, paddingBottom: 32, paddingTop: 10, gap: 14 }, handle: { width: 42, height: 5, borderRadius: 3, backgroundColor: '#3E4550', alignSelf: 'center', marginBottom: 8 }, sheetTitle: { color: palette.text, fontSize: 24, fontWeight: '800', marginBottom: 4 }, input: { minHeight: 54, borderRadius: 16, paddingHorizontal: 16, backgroundColor: palette.panel2, color: palette.text, fontSize: 16, borderWidth: 1, borderColor: palette.border }, button: { minHeight: 56, borderRadius: 18, alignItems: 'center', justifyContent: 'center', marginTop: 4 }, buttonText: { color: '#101409', fontWeight: '900', fontSize: 16 } });
